// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbgFdqLbFsASO6cAAErzcgy1tCb6WPEYo',
    databaseURL:
        "https://flutterfirst-8683c-default-rtdb.asia-southeast1.firebasedatabase.app",
    appId: '1:517657616007:web:3be28b6ad4b861cddf6222',
    messagingSenderId: '517657616007',
    projectId: 'flutterfirst-8683c',
    authDomain: 'flutterfirst-8683c.firebaseapp.com',
    storageBucket: 'flutterfirst-8683c.appspot.com',
    measurementId: 'G-S7515SYWPJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDE9lhpUHs8uv6Nb7VSFhrqx-AH9viJ7GA',
    appId: '1:517657616007:android:ce928fd3614d5c88df6222',
    messagingSenderId: '517657616007',
    projectId: 'flutterfirst-8683c',
    storageBucket: 'flutterfirst-8683c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMoUov9GKiinqecShmhF4xvsZWujQqS0A',
    appId: '1:517657616007:ios:a786d63965f2e0e2df6222',
    messagingSenderId: '517657616007',
    projectId: 'flutterfirst-8683c',
    storageBucket: 'flutterfirst-8683c.appspot.com',
    iosBundleId: 'com.example.firebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAMoUov9GKiinqecShmhF4xvsZWujQqS0A',
    appId: '1:517657616007:ios:a786d63965f2e0e2df6222',
    messagingSenderId: '517657616007',
    projectId: 'flutterfirst-8683c',
    storageBucket: 'flutterfirst-8683c.appspot.com',
    iosBundleId: 'com.example.firebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBbgFdqLbFsASO6cAAErzcgy1tCb6WPEYo',
    appId: '1:517657616007:web:d46e4beb815ebafbdf6222',
    messagingSenderId: '517657616007',
    projectId: 'flutterfirst-8683c',
    authDomain: 'flutterfirst-8683c.firebaseapp.com',
    storageBucket: 'flutterfirst-8683c.appspot.com',
    measurementId: 'G-ZB4T7DJ6LW',
  );
}
